'use strict';

module.exports = {
  rules: {
    'angular/angularelement': 0,
    'angular/controller_as': 0,
    'angular/controller_as_route': 0,
    'angular/controller_as_vm': 0,
    'angular/controller_name': 0,
    'angular/deferred': 0,
    'angular/definedundefined': 0,
    'angular/di': 0,
    'angular/directive_name': 0,
    'angular/document_service': 0,
    'angular/empty_controller': 0,
    'angular/foreach': 0,
    'angular/filter_name': 0,
    'angular/function_type': 0,
    'angular/interval_service': 0,
    'angular/json_functions': 0,
    'angular/module_getter': 0,
    'angular/module_name': 0,
    'angular/module_setter': 0,
    'angular/no_angular_mock': 0,
    'angular/no_cookiestore': 0,
    'angular/no_digest': 0,
    'angular/no_jquery_angularelement': 0,
    'angular/no_private_call': 0,
    'angular/no_services': 0,
    'angular/no_service_method': 0,
    'angular/on_watch': 0,
    'angular/service_name': 0,
    'angular/timeout_service': 0,
    'angular/typecheck_array': 0,
    'angular/typecheck_date': 0,
    'angular/typecheck_function': 0,
    'angular/typecheck_number': 0,
    'angular/typecheck_object': 0,
    'angular/typecheck_regexp': 0,
    'angular/typecheck_string': 0,
    'angular/window_service': 0
  }
};